import datetime

x = datetime.datetime.now()

print(x.year)
print(x.strftime("%A"))
print(x.strftime("%m"))
print(x.strftime("%w"))
print(x.strftime("%B"))
print(x.strftime("%b"))
print(x.strftime("%y"))
print(x.strftime("%Y"))
print(x.strftime("%H"))
print(x.strftime("%I"))
print(x.strftime("%p"))
print(x.strftime("%M"))
print(x.strftime("%S"))
print(x.strftime("%f"))
print(x.strftime("%z"))
print(x.strftime("%Z"))
print(x.strftime("%j"))